version: '3.9'

services:
  app:
    build:
      context: ./ReadyToHelpAPI
      dockerfile: Dockerfile
    container_name: r2h_api
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: readytohelp
      POSTGRES_PASSWORD: readytohelppwd
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - r2h_network

  postgres:
    container_name: r2h_postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: readytohelp
      POSTGRES_PASSWORD: readytohelppwd
      POSTGRES_DB: readytohelp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - r2h_network

volumes:
  postgres_data:
    external: true

networks:
  r2h_network:
    external: true