services:
  app:
    build:
      context: ./ReadyToHelpAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: readytohelp
      POSTGRES_PASSWORD: readytohelppwd
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: readytohelp
      POSTGRES_PASSWORD: readytohelppwd
      POSTGRES_DB: readytohelp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: